### ISSUE TITLE
Shortcode attribute to define location(s)

### ISSUE THREAD

**Issue by kimmenbert** [booqable/wordpress-plugin#14]
Hi, We have a client using your plugin, they have set up locations in Booqable, but not every location is for every product.

Is there a way to define what locations should be selectable per [booqable_datepicker]?

**Comment by dabrorius** [comment]
Unfortunately I don't think that's possible. You can always reach out to the Booqable tech support team directly and they will be able to guide you more directly to alternative solutions. https://help.booqable.com/en/
