### ISSUE TITLE
Wrong/outdated instructions to get Company ID

### ISSUE THREAD

**Issue by pilaf** [booqable/wordpress-plugin#2]
The instructions in the plugin say to go to **Settings > Shop**, yet that option doesn't exist. Instead one has to go to **Settings > Online reservations > Install on WordPress** to find the Company ID.

![Screen Shot 2019-08-02 at 17 24 28](https://user-images.githubusercontent.com/38060/62396822-80864000-b54a-11e9-9e4c-24571668caf9.png)

**Comment by reinaris** [comment]
I just checked, and in the meantime 🕐 the instructions were updated, so I'll close this issue. 👍
